name: SupremeCore
version: ${project.version}
main: net.supremesurvival.supremecore.SupremeCore
api-version: 1.16
authors: [ xMachiavellix ]
description: Core API for SupremeNetwork
softdepend: [PlaceholderAPI] # This is used, if your plugin works without PlaceholderAPI.
commands:
  HorseInfo:
    description: Your description
    usage: /horseinfo
  timevote:
    aliases: [tv]
  weathervote:
    aliases: [wv]