name: SupremeCore
version: 1.0-SNAPSHOT
main: net.supremesurvival.supremecore.SupremeCore
api-version: 1.16
authors: [ xMachiavellix ]
description: Core API for SupremeNetwork
softdepend: [PlaceholderAPI]
depend: [WorldGuard]
permissions:
  announcer.send:
    description: send an announcement to all players.
    default:  op
  tomes.retrieve:
    description: retrieves all tomes.
    default:  op
commands:
  HorseInfo:
    description: Your description
    usage: /horseinfo
  Announcer:
    description: Command interface for the interval announcer class and related functionality.
    aliases: [aa]
  Tomes:
    description: manages custom tomes
    permission: tomes.retrieve
  Artefacts:
    description: custom items
  Landmarks:
    description: lists landmarks
    permission: landmarks.list
