name: SupremeCore
version: 1.0-SNAPSHOT
main: net.supremesurvival.supremecore.SupremeCore
api-version: 1.16
authors: [ xMachiavellix ]
description: Core API for SupremeNetwork
commands:
  HorseInfo:
    description: Your description
    usage: /horseinfo
  timevote:
    aliases: [tv]
  weathervote:
    aliases: [wv]